print('Two roads diverged in a yellow wood,')
print('And sorry I could not travel both')
print('And be one traveler, long I stood,')
print('And looked down one as far as I could,')
print('To where it bent in the undergrowth.')